FROM ros:humble

# Set environment variables for display
ENV DISPLAY=${DISPLAY}
ENV QT_X11_NO_MITSHM=1
ENV DEBIAN_FRONTEND=noninteractive

# Install ROS 2 desktop and Gazebo 11
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-opencv \
    ros-humble-desktop \
    gazebo \
    ros-humble-ros-gz \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/*

# Create workspace
WORKDIR /ros_ws

# Setup shell environment
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

# Default command
CMD ["bash"] 