# Position Controllers ---------------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Position Controllers ---------------------------------------
joint1_position_controller:
  type: effort_controllers/JointPositionController
  joint: lf_joint1
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint2_position_controller:
  type: effort_controllers/JointPositionController
  joint: rf_joint1
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint3_position_controller:
  type: effort_controllers/JointPositionController
  joint: lb_joint1
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint4_position_controller:
  type: effort_controllers/JointPositionController
  joint: rb_joint1
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: lf_joint2
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint6_position_controller:
  type: effort_controllers/JointPositionController
  joint: rf_joint2
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint7_position_controller:
  type: effort_controllers/JointPositionController
  joint: lb_joint2
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57

joint8_position_controller:
  type: effort_controllers/JointPositionController
  joint: rb_joint2
  pid: {p: 3.0, i: 0, d: 0, i_clamp_min: -1000, i_clamp_max: 1000}
  max_velocity: 1.0
  min_velocity: -1.0
  max_position: 1.57
  min_position: -1.57
