topics:
- name    : navigation
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 10

- name    : keyboard
  topic   : cmd_vel/keyboard
  timeout : 0.5
  priority: 100

- name    : joystick
  topic   : cmd_vel/joy
  timeout : 0.5
  priority: 100

locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255