gazebo_ros_control:
  pid_gains:
    lf_hip_joint: {p: 180.0, i: 0.0, d: 12.0}
    lf_upper_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    lf_lower_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    rf_hip_joint: {p: 180.0, i: 0.0, d: 12.0}
    rf_upper_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    rf_lower_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    lh_hip_joint: {p: 180.0, i: 0.0, d: 12.0}
    lh_upper_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    lh_lower_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    rh_hip_joint: {p: 180.0, i: 0.0, d: 12.0}
    rh_upper_leg_joint: {p: 180.0, i: 0.0, d: 12.0}
    rh_lower_leg_joint: {p: 180.0, i: 0.0, d: 12.0}