controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

effort_controllers:
  ros__parameters:
    joints:
      - lf_joint1
      - lf_joint2
      - lb_joint1
      - lb_joint2
      - rf_joint1
      - rf_joint2
      - rb_joint1
      - rb_joint2
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

position_controllers:
  ros__parameters:
    joints:
      - lf_joint1
      - lf_joint2
      - lb_joint1
      - lb_joint2
      - rf_joint1
      - rf_joint2
      - rb_joint1
      - rb_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - lf_joint1
      - lf_joint2
      - rf_joint1
      - rf_joint2
      - lb_joint1
      - lb_joint2
      - rb_joint1
      - rb_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      lf_joint1: { trajectory: 0.1, goal: 0.1 }
      lf_joint2: { trajectory: 0.1, goal: 0.1 }
      rf_joint1: { trajectory: 0.1, goal: 0.1 }
      rf_joint2: { trajectory: 0.1, goal: 0.1 }
      lb_joint1: { trajectory: 0.1, goal: 0.1 }
      lb_joint2: { trajectory: 0.1, goal: 0.1 }
      rb_joint1: { trajectory: 0.1, goal: 0.1 }
      rb_joint2: { trajectory: 0.1, goal: 0.1 } 